kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      # Map host 80 → Traefik NodePort 30080
      - containerPort: 30080
        hostPort: 80
        protocol: TCP
      # Map host 443 → Traefik NodePort 30443
      - containerPort: 30443
        hostPort: 443
        protocol: TCP

